// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzUDgcq1qq2_ustdYerVGxuSaozifbqbg',
    appId: '1:256162245053:web:89e68f63fc75449bb28ad4',
    messagingSenderId: '256162245053',
    projectId: 'todolist-14d18',
    authDomain: 'todolist-14d18.firebaseapp.com',
    storageBucket: 'todolist-14d18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA6pqVlGOpWv-jbhK57HgRGaiePO0aZmU',
    appId: '1:256162245053:android:7ff7f5bd349e55b3b28ad4',
    messagingSenderId: '256162245053',
    projectId: 'todolist-14d18',
    storageBucket: 'todolist-14d18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGAlWVKn2LHPqn6nPp83Ivty4eQ_7qb8g',
    appId: '1:256162245053:ios:d2d014ac178c6b00b28ad4',
    messagingSenderId: '256162245053',
    projectId: 'todolist-14d18',
    storageBucket: 'todolist-14d18.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGAlWVKn2LHPqn6nPp83Ivty4eQ_7qb8g',
    appId: '1:256162245053:ios:d2d014ac178c6b00b28ad4',
    messagingSenderId: '256162245053',
    projectId: 'todolist-14d18',
    storageBucket: 'todolist-14d18.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzUDgcq1qq2_ustdYerVGxuSaozifbqbg',
    appId: '1:256162245053:web:4ab3843be8eb8b74b28ad4',
    messagingSenderId: '256162245053',
    projectId: 'todolist-14d18',
    authDomain: 'todolist-14d18.firebaseapp.com',
    storageBucket: 'todolist-14d18.firebasestorage.app',
  );
}
